import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:velocity_x/velocity_x.dart';
import 'package:viha_tech/core/constants/my_colors.dart';
import 'package:viha_tech/data/repositories/repositories.dart';
import 'package:viha_tech/presentation/routes/router_imports.gr.dart';
import 'package:viha_tech/presentation/screens/register/register_view_model.dart';
part 'register.dart';
